// ============================================================================
//  CONFIG / BANCO DE FRASES
//  ----------------------------------------------------------------------------
//  Contiene todo el contenido educativo del juego, organizado en 6 Misiones.
//  Cada frase incluye:
//    sentence   -> la oración con el hueco (____)
//    answer     -> el verbo conjugado correcto (nivel A1, presente de indicativo)
//    column     -> la columna resaltada (1-4) donde debe ir la respuesta
//    distractors-> 3 verbos distractores para rellenar las demás celdas
//    hint       -> traducción / pista en ruso para el estudiante
//
//  Todos los archivos JS de este proyecto usan módulos ES nativos.
// ============================================================================

export const MISSIONS = [
  {
    id: 1,
    name: 'En el supermercado',
    emoji: '🛒',
    desc: 'Comprar, pagar, llevar...',
    color: '#00e5ff',
    verbs: ['comprar', 'pagar', 'llevar', 'querer', 'costar'],
    // Recompensa automática al completar esta misión (sin coste)
    reward: { coins: 50, theme: null, speedBonus: false, consumable: null },
    phrases: [
      {
        sentence: 'Yo ____ pan en el supermercado.',
        answer: 'compro',
        column: 2,
        distractors: ['compras', 'compra', 'quiere'],
        hint: 'Я покупаю хлеб в супермаркете.',
      },
      {
        sentence: 'Tú ____ en la caja.',
        answer: 'pagas',
        column: 1,
        distractors: ['pago', 'paga', 'compra'],
        hint: 'Ты платишь на кассе.',
      },
      {
        sentence: 'Yo ____ la bolsa.',
        answer: 'llevo',
        column: 3,
        distractors: ['lleva', 'llevas', 'pago'],
        hint: 'Я несу сумку.',
      },
      {
        sentence: 'Nosotros ____ pan y leche.',
        answer: 'compramos',
        column: 4,
        distractors: ['compro', 'compra', 'pagamos'],
        hint: 'Мы покупаем хлеб и молоко.',
      },
      {
        sentence: 'Él ____ pagar con tarjeta.',
        answer: 'quiere',
        column: 1,
        distractors: ['quiero', 'quieres', 'paga'],
        hint: 'Он хочет заплатить картой.',
      },
      {
        sentence: '¿Cuánto ____ la manzana?',
        answer: 'cuesta',
        column: 2,
        distractors: ['cuestan', 'compra', 'lleva'],
        hint: 'Сколько стоит яблоко?',
      },
      {
        sentence: 'Yo ____ comprar fruta fresca.',
        answer: 'quiero',
        column: 3,
        distractors: ['quiere', 'quieres', 'compro'],
        hint: 'Я хочу купить свежие фрукты.',
      },
      {
        sentence: 'Tú ____ dos bolsas grandes.',
        answer: 'llevas',
        column: 4,
        distractors: ['llevo', 'lleva', 'compras'],
        hint: 'Ты несёшь две большие сумки.',
      },
      {
        sentence: 'Ellos ____ verduras.',
        answer: 'compran',
        column: 1,
        distractors: ['compra', 'compro', 'pagan'],
        hint: 'Они покупают овощи.',
      },
      {
        sentence: 'Las manzanas ____ poco.',
        answer: 'cuestan',
        column: 2,
        distractors: ['cuesta', 'quieren', 'compran'],
        hint: 'Яблоки стоят немного.',
      },
    ],
  },

  {
    id: 2,
    name: 'En el restaurante',
    emoji: '🍽️',
    desc: 'Pedir, comer, beber...',
    color: '#ff2d95',
    verbs: ['pedir', 'comer', 'beber', 'traer', 'probar'],
    // Al completar: +50 monedas y se desbloquea el tema estético "Retro"
    reward: { coins: 50, theme: 'retro', speedBonus: false, consumable: null },
    phrases: [
      {
        sentence: 'Yo ____ un plato de paella.',
        answer: 'pido',
        column: 1,
        distractors: ['pides', 'pide', 'como'],
        hint: 'Я заказываю тарелку паэльи.',
      },
      {
        sentence: 'Tú ____ mucha fruta.',
        answer: 'comes',
        column: 2,
        distractors: ['como', 'come', 'bebes'],
        hint: 'Ты ешь много фруктов.',
      },
      {
        sentence: 'Yo ____ agua con hielo.',
        answer: 'bebo',
        column: 3,
        distractors: ['bebes', 'bebe', 'pido'],
        hint: 'Я пью воду со льдом.',
      },
      {
        sentence: 'Él ____ los platos.',
        answer: 'trae',
        column: 4,
        distractors: ['traigo', 'traes', 'pide'],
        hint: 'Он приносит блюда.',
      },
      {
        sentence: 'Nosotros ____ el postre.',
        answer: 'probamos',
        column: 2,
        distractors: ['pruebo', 'pruebas', 'comemos'],
        hint: 'Мы пробуем десерт.',
      },
      {
        sentence: 'Ellos ____ pescado.',
        answer: 'piden',
        column: 2,
        distractors: ['pides', 'pide', 'traen'],
        hint: 'Они заказывают рыбу.',
      },
      {
        sentence: 'Tú ____ vino tinto.',
        answer: 'bebes',
        column: 3,
        distractors: ['bebo', 'bebe', 'pides'],
        hint: 'Ты пьёшь красное вино.',
      },
      {
        sentence: 'Yo ____ comida española.',
        answer: 'como',
        column: 4,
        distractors: ['comes', 'come', 'bebo'],
        hint: 'Я ем испанскую еду.',
      },
      {
        sentence: 'Nosotros ____ la paella.',
        answer: 'pedimos',
        column: 1,
        distractors: ['pido', 'pides', 'comemos'],
        hint: 'Мы заказываем паэлью.',
      },
      {
        sentence: 'El chef ____ la sopa.',
        answer: 'prueba',
        column: 2,
        distractors: ['pruebo', 'pruebas', 'bebe'],
        hint: 'Шеф пробует суп.',
      },
    ],
  },

  {
    id: 3,
    name: 'En el hotel',
    emoji: '🏨',
    desc: 'Reservar, llegar, dormir...',
    color: '#ff9100',
    verbs: ['reservar', 'llegar', 'dormir', 'despertarse', 'necesitar'],
    // Al completar: +50 monedas y una reducción temporal de velocidad
    reward: { coins: 50, theme: null, speedBonus: true, consumable: null },
    phrases: [
      {
        sentence: 'Yo ____ una habitación.',
        answer: 'reservo',
        column: 1,
        distractors: ['reservas', 'reserva', 'necesito'],
        hint: 'Я бронирую номер.',
      },
      {
        sentence: 'Tú ____ al hotel.',
        answer: 'llegas',
        column: 2,
        distractors: ['llego', 'llega', 'necesitas'],
        hint: 'Ты прибываешь в отель.',
      },
      {
        sentence: 'Yo ____ en una cama grande.',
        answer: 'duermo',
        column: 3,
        distractors: ['duermes', 'duerme', 'reservo'],
        hint: 'Я сплю на большой кровати.',
      },
      {
        sentence: 'Él ____ a las ocho.',
        answer: 'se despierta',
        column: 4,
        distractors: ['me despierto', 'te despiertas', 'llega'],
        hint: 'Он просыпается в восемь.',
      },
      {
        sentence: 'Nosotros ____ dos maletas.',
        answer: 'necesitamos',
        column: 2,
        distractors: ['necesito', 'necesita', 'llegamos'],
        hint: 'Нам нужны два чемодана.',
      },
      {
        sentence: 'Yo ____ hablar con el recepcionista.',
        answer: 'necesito',
        column: 1,
        distractors: ['necesitas', 'necesita', 'reservo'],
        hint: 'Мне нужно поговорить с администратором.',
      },
      {
        sentence: 'Tú ____ en el piso dos.',
        answer: 'duermes',
        column: 3,
        distractors: ['duermo', 'duerme', 'llegas'],
        hint: 'Ты спишь на втором этаже.',
      },
      {
        sentence: 'Ella ____ la habitación doble.',
        answer: 'reserva',
        column: 4,
        distractors: ['reservo', 'reservas', 'necesita'],
        hint: 'Она бронирует двухместный номер.',
      },
      {
        sentence: 'Nosotros ____ temprano.',
        answer: 'llegamos',
        column: 1,
        distractors: ['llego', 'llegas', 'dormimos'],
        hint: 'Мы приезжаем рано.',
      },
      {
        sentence: 'Yo ____ a las siete.',
        answer: 'me despierto',
        column: 2,
        distractors: ['se despierta', 'te despiertas', 'duermo'],
        hint: 'Я просыпаюсь в семь.',
      },
    ],
  },

  {
    id: 4,
    name: 'En la farmacia',
    emoji: '💊',
    desc: 'Doler, tomar, recetar...',
    color: '#aaff00',
    verbs: ['doler', 'tomar', 'recetar', 'sentir', 'mejorar'],
    // Al completar: +50 monedas y un uso gratis de la "Pista Visual"
    reward: { coins: 50, theme: null, speedBonus: false, consumable: 'pista' },
    phrases: [
      {
        sentence: 'Me ____ la cabeza.',
        answer: 'duele',
        column: 1,
        distractors: ['duelen', 'tomo', 'siento'],
        hint: 'У меня болит голова.',
      },
      {
        sentence: 'Tú ____ una pastilla.',
        answer: 'tomas',
        column: 2,
        distractors: ['tomo', 'toma', 'sientes'],
        hint: 'Ты принимаешь таблетку.',
      },
      {
        sentence: 'El médico ____ un jarabe.',
        answer: 'receta',
        column: 3,
        distractors: ['receto', 'recetas', 'mejora'],
        hint: 'Врач выписывает сироп.',
      },
      {
        sentence: 'Yo ____ mejor hoy.',
        answer: 'me siento',
        column: 4,
        distractors: ['se siente', 'te sientes', 'tomo'],
        hint: 'Я чувствую себя лучше сегодня.',
      },
      {
        sentence: 'Tú ____ mucho.',
        answer: 'mejoras',
        column: 2,
        distractors: ['mejora', 'mejoro', 'tomas'],
        hint: 'Ты идёшь на поправку.',
      },
      {
        sentence: 'Yo ____ la medicina cada día.',
        answer: 'tomo',
        column: 1,
        distractors: ['tomas', 'toma', 'receto'],
        hint: 'Я принимаю лекарство каждый день.',
      },
      {
        sentence: 'Le ____ los pies.',
        answer: 'duelen',
        column: 3,
        distractors: ['duele', 'tomo', 'siento'],
        hint: 'У него болят ноги.',
      },
      {
        sentence: 'Nosotros ____ bien.',
        answer: 'nos sentimos',
        column: 4,
        distractors: ['me siento', 'se sienten', 'tomamos'],
        hint: 'Мы чувствуем себя хорошо.',
      },
      {
        sentence: 'Ellos ____ medicina.',
        answer: 'toman',
        column: 1,
        distractors: ['tomo', 'tomas', 'mejoran'],
        hint: 'Они принимают лекарство.',
      },
      {
        sentence: 'Tú ____ mejor mañana.',
        answer: 'te sientes',
        column: 2,
        distractors: ['me siento', 'se siente', 'tomas'],
        hint: 'Завтра тебе станет лучше.',
      },
    ],
  },

  {
    id: 5,
    name: 'Pidiendo direcciones',
    emoji: '🗺️',
    desc: 'Ir, seguir, girar, cruzar...',
    color: '#9d4dff',
    verbs: ['ir', 'seguir', 'girar', 'cruzar', 'buscar', 'estar'],
    // Al completar: +50 monedas y se desbloquea el tema estético "Fiesta"
    reward: { coins: 50, theme: 'fiesta', speedBonus: false, consumable: null },
    phrases: [
      {
        sentence: 'Yo ____ al banco.',
        answer: 'voy',
        column: 1,
        distractors: ['vas', 'va', 'sigue'],
        hint: 'Я иду в банк.',
      },
      {
        sentence: 'Tú ____ todo recto.',
        answer: 'sigues',
        column: 2,
        distractors: ['sigo', 'sigue', 'giras'],
        hint: 'Ты идёшь всё прямо.',
      },
      {
        sentence: 'Yo ____ a la derecha.',
        answer: 'giro',
        column: 3,
        distractors: ['giras', 'gira', 'voy'],
        hint: 'Я поворачиваю направо.',
      },
      {
        sentence: 'Él ____ la calle.',
        answer: 'cruza',
        column: 4,
        distractors: ['cruzo', 'cruzas', 'sigue'],
        hint: 'Он переходит улицу.',
      },
      {
        sentence: 'Nosotros ____ el supermercado.',
        answer: 'buscamos',
        column: 2,
        distractors: ['busco', 'busca', 'vamos'],
        hint: 'Мы ищем супермаркет.',
      },
      {
        sentence: '¿Dónde ____ la estación?',
        answer: 'está',
        column: 1,
        distractors: ['estoy', 'estás', 'voy'],
        hint: 'Где находится станция?',
      },
      {
        sentence: 'Tú ____ a la izquierda.',
        answer: 'giras',
        column: 3,
        distractors: ['giro', 'gira', 'cruzas'],
        hint: 'Ты поворачиваешь налево.',
      },
      {
        sentence: 'Ellos ____ al parque.',
        answer: 'van',
        column: 4,
        distractors: ['voy', 'vas', 'cruzan'],
        hint: 'Они идут в парк.',
      },
      {
        sentence: 'Yo ____ buscando la farmacia.',
        answer: 'estoy',
        column: 1,
        distractors: ['está', 'estás', 'voy'],
        hint: 'Я ищу аптеку.',
      },
      {
        sentence: 'Nosotros ____ hasta la plaza.',
        answer: 'vamos',
        column: 2,
        distractors: ['voy', 'va', 'buscamos'],
        hint: 'Мы идём до площади.',
      },
    ],
  },

  {
    id: 6,
    name: 'De compras (ropa)',
    emoji: '👕',
    desc: 'Probarse, comprar, usar...',
    color: '#00ffc8',
    verbs: ['probarse', 'comprar', 'mirar', 'usar', 'llevar puesto'],
    // Al completar (fin del juego): +50 monedas, tema "Neón Rey" y modo Zen
    reward: {
      coins: 50,
      theme: 'neon',
      speedBonus: false,
      consumable: null,
      zen: true,
    },
    phrases: [
      {
        sentence: 'Yo ____ este vestido.',
        answer: 'me pruebo',
        column: 1,
        distractors: ['te pruebas', 'se prueba', 'miro'],
        hint: 'Я примеряю это платье.',
      },
      {
        sentence: 'Tú ____ una camiseta azul.',
        answer: 'compras',
        column: 2,
        distractors: ['compro', 'compra', 'miras'],
        hint: 'Ты покупаешь синюю футболку.',
      },
      {
        sentence: 'Yo ____ los zapatos.',
        answer: 'miro',
        column: 3,
        distractors: ['miras', 'mira', 'uso'],
        hint: 'Я смотрю на туфли.',
      },
      {
        sentence: 'Él ____ un abrigo.',
        answer: 'lleva puesto',
        column: 4,
        distractors: ['llevo puesto', 'llevas puesto', 'usa'],
        hint: 'Он носит пальто.',
      },
      {
        sentence: 'Yo ____ ropa nueva.',
        answer: 'uso',
        column: 2,
        distractors: ['usas', 'usa', 'compro'],
        hint: 'Я ношу новую одежду.',
      },
      {
        sentence: 'Tú ____ unos pantalones negros.',
        answer: 'te pruebas',
        column: 1,
        distractors: ['me pruebo', 'se prueba', 'usas'],
        hint: 'Ты примеряешь чёрные брюки.',
      },
      {
        sentence: 'Nosotros ____ zapatos grandes.',
        answer: 'miramos',
        column: 3,
        distractors: ['miro', 'miras', 'compramos'],
        hint: 'Мы смотрим на большие туфли.',
      },
      {
        sentence: 'Ellos ____ una falda corta.',
        answer: 'compran',
        column: 4,
        distractors: ['compro', 'compra', 'miran'],
        hint: 'Они покупают короткую юбку.',
      },
      {
        sentence: 'Yo ____ una blusa blanca.',
        answer: 'compro',
        column: 1,
        distractors: ['compras', 'compra', 'uso'],
        hint: 'Я покупаю белую блузку.',
      },
      {
        sentence: 'Tú ____ un sombrero bonito.',
        answer: 'llevas puesto',
        column: 2,
        distractors: ['llevo puesto', 'lleva puesto', 'pruebas'],
        hint: 'Ты носишь красивую шляпу.',
      },
    ],
  },
];
